export const AUTH_CHANGE_FIELDS = "AUTH_CHANGE_FIELDS"
export const AUTH_CHANGE_REGISTER_FIELDS = "AUTH_CHANGE_REGISTER_FIELDS"

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_FULFILLED = 'AUTH_LOGIN_FULFILLED'
export const AUTH_LOGIN_REJECTED = 'AUTH_LOGIN_REJECTED'

export const AUTH_LOGOUT = "AUTH_LOGOUT"


export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST'
export const AUTH_REGISTER_FULFILLED = 'AUTH_REGISTER_FULFILLED'
export const AUTH_REGISTER_REJECTED = 'AUTH_REGISTER_REJECTED'